# Site
name: "Legal Clinic"
title: ཁྲིམས་གླེང་གི་བློ་འདྲི་བྱེད་ས།
description: "ཁྱེད་རང་ལ་བོད་སྐད་ཡིག་གི་སྟེང་ནས་ཁྲིམས་ལུགས་རོགས་རམ་བྱེད་དགོས་བྱུང་ཚེ། གལ་ཏེ་ཁྱེད་ཀྱི་གནད་དོན་དང་དྲི་བ་དེ་དག་གཤམ་གྱི་སྡེ་ཚན་གང་རུང་དུ་གཏོགས་ཚེ། སྡེ་ཚེན་དེའི་འབྲེལ་གྱི་དྲ་ཐག་ལ་བསྣུན་ན་ཁྱེད་ཀྱི་དྲི་བ་དང་བསྟུན་པའི་ལན་དང་དྲི་བ་ལ་འབྲེལ་བ་ཡོད་པའི་ཡིག་ཆ་སོགས་ཤར་ཡོང་། ཁྲིམས་གླེང་གིས་ཐད་གར་དྲི་བ་འདི་དག་ལ་ལན་མི་ལྡོན།་"
meta_description: "ཁྱེད་རང་ལ་བོད་སྐད་ཡིག་གི་སྟེང་ནས་ཁྲིམས་ལུགས་རོགས་རམ་བྱེད་དགོས་བྱུང་ཚེ། གལ་ཏེ་ཁྱེད་ཀྱི་གནད་དོན་དང་དྲི་བ་དེ་དག་གཤམ་གྱི་སྡེ་ཚན་གང་རུང་དུ་གཏོགས་ཚེ། སྡེ་ཚེན་དེའི་འབྲེལ་གྱི་དྲ་ཐག་ལ་བསྣུན་ན་ཁྱེད་ཀྱི་དྲི་བ་དང་བསྟུན་པའི་ལན་དང་དྲི་བ་ལ་འབྲེལ་བ་ཡོད་པའི་ཡིག་ཆ་སོགས་ཤར་ཡོང་། ཁྲིམས་གླེང་གིས་ཐད་གར་དྲི་བ་འདི་དག་ལ་ལན་མི་ལྡོན།"
google_analytics: UA-83909662-2

og_banner: "/assets/images/banner.jpg"
#logo: 
#favicon: 
baseurl: "https://trim-leng.github.io/legalclinic/"
#google_analytics: ''
auto-regeneration: --watch

paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    

  
    
# Other
markdown: kramdown
highlighter: rouge